language: cpp
compiler:
  - gcc
  - clang
env:
    global:
       # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
       #   via the "travis encrypt" command using the project repo's public key
       - secure: "SodOHkeIggfLhzWD2kxbmHWcbqhOZzL5/5RFxUH+wPtj4VArxeTWCklSAn5BjrSZN9ljVf+lArt4L238odotLhCa9UXjvuPOFVQ+nAGw7XNjso/ccu1ce9cClv+Dzlc8NVJx0tApGZqJjscYesfw/Ij2fN21iwk/U736E08ya9I="

  # These are used by .travis-cmake.sh to set a configuration
  - CMS_CONFIG=NORMAL
#  - CMS_CONFIG=STATIC_BIN
  - CMS_CONFIG=ONLY_SIMPLE
#  - CMS_CONFIG=ONLY_SIMPLE_STATIC
  - CMS_CONFIG=MORE_DEBUG
  - CMS_CONFIG=STATS
  - CMS_CONFIG=NOZLIB
  - CMS_CONFIG=RELEASE
  - CMS_CONFIG=NOSQLITE
  - CMS_CONFIG=NOMYSQL
  - CMS_CONFIG=NOMYSQLNOSQLITE
  - CMS_CONFIG=PYTHON
  - CMS_CONFIG=MYSQL
  - CMS_CONFIG=SQLITE
  - CMS_CONFIG=M4RI
  - CMS_CONFIG=WEB
  - CMS_CONFIG=SLOW_DEBUG
  - CMS_CONFIG=AWS

addons:
  coverity_scan:
    project:
      name: "msoos/cryptominisat"
      description: "Advanced SAT solver"
    notification_email: soos.mate@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake .."
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
install:
  - sudo apt-get install libboost-test-dev gcc-4.7 g++-4.7
  - sudo apt-get remove g++-4.6 gcc-4.6
  - sudo apt-get install cmake valgrind
  - sudo pip install lit
#
#get lingeling
  - git clone https://github.com/msoos/lingeling-ala
  - cd lingeling-ala
  - ./configure
  - make
  - sudo cp lingeling /usr/local/bin/
  - cd ..
#
#get drat-trim
  - git clone https://github.com/msoos/drat
  - cd drat
  - make
  - sudo cp drat-trim /usr/local/bin/
  - cd ..
#
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
script:
  - ../.travis-cmake.sh ../ build

